import './globals.css';
import { MswComponent } from '@/components/util/msw-component';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MswComponent />
        {children}
      </body>
    </html>
  );
}
